### ISSUE TITLE
Unable to find a specification for `CRNotifications`

### ISSUE THREAD

**Issue by himanshupadia** [dkcas11/CRNotifications#10]
Getting error while `pod install`
 [!] Unable to find a specification for `CRNotifications`
do needful.

**Comment by dkcas11** [comment]
Have you tried to clean the specs repo?
Run these two commands from the Terminal:
pod repo remove master
pod setup

**Comment by dkcas11** [comment]
Since this issue is fairly old and you have yet to respond I assume this matter is resolved and hereby closes this issue.
