### ISSUE TITLE
New logo/Icon

### ISSUE THREAD

**Issue by mansya** [dkcas11/CRNotifications#14]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, your logo on this project not attractive . Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by saldous** [comment]
IMO, Go for it!

**Comment by dkcas11** [comment]
Sure, lets give it a try 😃

**Comment by mansya** [comment]
I have design logo for this project. what dou you think ? do you like it ?
![crnotification](https://user-images.githubusercontent.com/33461607/42613926-93b93a54-85cd-11e8-8951-5cf0be21374b.png)

sorry for late response

**Comment by dkcas11** [comment]
To be honest i am not really a huge fan of that gradient and font :-) 
CRNotifications*

**Comment by mansya** [comment]
Should I use only material colors?

**Comment by mansya** [comment]
how about this ? do you like it ?
![crnotification](https://user-images.githubusercontent.com/33461607/42633346-6f5a8c66-860a-11e8-81be-9a7744d2ff83.png)

or you can give me color code RGB

**Comment by saldous** [comment]
@mansya I thought you were talking about these icons:
![image](https://user-images.githubusercontent.com/3334306/42634833-5503405e-85b2-11e8-94db-ea39a315306b.png)

**Comment by mansya** [comment]
I design for the app icon.
do you also want me to design a logo for that in red box too?
