### ISSUE TITLE
Notifications get cut in iPhoneX.

### ISSUE THREAD

**Issue by ambujshukla-cdn** [dkcas11/CRNotifications#16]
Hi, please have a look in this issue. As the notifications get cut on top in iPhoneX.

**Comment by dkcas11** [comment]
Can you provide some more detail on this. Currently this is how it looks when i run it.
<img width="244" alt="screen shot 2018-09-03 at 09 56 41" src="https://user-images.githubusercontent.com/5683004/44974420-e72c6380-af5f-11e8-86d7-f2536c4cb304.png">
<img width="462" alt="screen shot 2018-09-03 at 09 57 53" src="https://user-images.githubusercontent.com/5683004/44974428-e98ebd80-af5f-11e8-82a4-7a3366f3bfd8.png">

**Comment by ambujshukla-cdn** [comment]
This is what I'm getting.
![screen shot 2018-09-03 at 3 10 30 pm](https://user-images.githubusercontent.com/24909778/44979765-916db080-af8b-11e8-9644-73528a4d54c4.png)

**Comment by ambujshukla-cdn** [comment]
I think I got the issue as in my attached screen the status bar is hidden that's why the notification is hiding under the notch in iPhoneX. The code inside the CRNotification is this - 			self.frame.origin.y = UIApplication.shared.statusBarFrame.height + 10
So I think this might the cause of issue.
So can you help me in this?

**Comment by dkcas11** [comment]
Aha. I will have a look at this when i got the time. I will try to see if i can do it tonight.

**Comment by ambujshukla-cdn** [comment]
Hi, did you get the time to look on this issue?

**Comment by dkcas11** [comment]
I have fixed it, will push it later today.

**Comment by ambujshukla-cdn** [comment]
Thanks a lot:)

**Comment by dkcas11** [comment]
Fixed in 1.1.6 🙂
