### ISSUE TITLE
Broken UI in iPhone XR and iPhone XS Max - iOS 12.1

### ISSUE THREAD

**Issue by chanonly123** [dkcas11/CRNotifications#21]
![iphone xr ios - 12 1](https://user-images.githubusercontent.com/13619184/49784542-ac4a8080-fd43-11e8-8c9e-259bcb7b71e5.png)
![iphone xs max - ios 12 1](https://user-images.githubusercontent.com/13619184/49784543-ac4a8080-fd43-11e8-8b47-bfbc20f0e1bf.png)

**Comment by dkcas11** [comment]
I actually knew this but never had the time to fix it, sadly. It's fixed now 👍
