### ISSUE TITLE
Adding repository to cocoapods

### ISSUE THREAD

**Issue by rico237** [dkcas11/CRNotifications#4]
Is it possible to had this project to cocoapods ?? 

I can help you do it if you don't know how :)

**Comment by dkcas11** [comment]
I have never done it before. Your help would be much appreciated :)

**Comment by rico237** [comment]
Ok no problems :) for this you need to add me to the project as a collaborator :)

**Comment by rico237** [comment]
So i add it to cocoapods repositories, we just have to wait until everyone can see it, for now you can use cocoapod with git url (like i wrote on the README file)

Success message when i pushed the repo :

<img width="589" alt="capture d ecran 2017-09-14 a 00 45 59" src="https://user-images.githubusercontent.com/4282169/30405277-30820210-98eb-11e7-9db5-9b28d7392b50.png">

**Comment by rico237** [comment]
I also made few changes to make it work (images wasn't accesible when used in pod framework)

**Comment by dkcas11** [comment]
Thanks for the help on the repository, i appreciate it 😉
I made two minor commits fixing an issue with the assets etc.. All i do is commit, for Cocapods to be updated, right?

**Comment by rico237** [comment]
No you should install cocoapods first in your mac,
then create an account with this command :
`pod trunk register casper2602@hotmail.com 'Casper Riboe' --description='macbook air'`
then when you confirm registration tell me so i can add you as a collaborator on the pod files
after that you'll be able to push to cocoapods

**Comment by rico237** [comment]
**Updating git project won't update cocoapods library !!**

you still have to push on cocoapods after every release ;)

**Comment by rico237** [comment]
you 'll have to update CRNotifications.podspec file with the correct version of project (the one you set on github)
then fix every warnings or error you face with this command : 
`pod spec lint CRNotifications.podspec`
then when everything passes you can push to cocoapods with this : 
`pod trunk push CRNotifications.podspec`

finally wait till changes are available on cocoapods main website ;)

**Comment by dkcas11** [comment]
Thanks for the little guide. I am not part of the owners, so i am not allowed to push the changes. Could you add me or tell me how i can add this? :)

**Comment by rico237** [comment]
yes, enter this command in your Terminal.app : 
pod trunk register casper2602@hotmail.com 'Casper Riboe' --description='macbook air'

when your done doing it i can add you as owner

**Comment by rico237** [comment]
I added you now you can push :)

**Comment by dkcas11** [comment]
Thanks, its pushed 😉

**Comment by dkcas11** [comment]
To update the repository to Swift 4, is it correct to open the workspace and update the Swift version in Build Settings, in the framework in the Pods project? I have made a branch for Swift 3 for anyone who would like to use that version.
