### ISSUE TITLE
.info image is upside down?

### ISSUE THREAD

**Issue by saldous** [dkcas11/CRNotifications#9]
Shouldn't the exclamation point in the .info notification type be the other way around?

<img width="366" alt="warning" src="https://user-images.githubusercontent.com/3334306/32334208-4537b76c-bfc0-11e7-9897-3add9df7ad85.png">

**Comment by dkcas11** [comment]
Its not an exclamation mark, it’s an “i” as in “info” 🙂

**Comment by saldous** [comment]
ah ok! 👍
